//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResearchersWPF.UI.svcResearcher {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Researcher", Namespace="http://schemas.datacontract.org/2004/07/ResearchersWPF.Service.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Researcher : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcademicDegreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResearcherIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcademicDegree {
            get {
                return this.AcademicDegreeField;
            }
            set {
                if ((object.ReferenceEquals(this.AcademicDegreeField, value) != true)) {
                    this.AcademicDegreeField = value;
                    this.RaisePropertyChanged("AcademicDegree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentNumber {
            get {
                return this.DepartmentNumberField;
            }
            set {
                if ((this.DepartmentNumberField.Equals(value) != true)) {
                    this.DepartmentNumberField = value;
                    this.RaisePropertyChanged("DepartmentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResearcherId {
            get {
                return this.ResearcherIdField;
            }
            set {
                if ((this.ResearcherIdField.Equals(value) != true)) {
                    this.ResearcherIdField = value;
                    this.RaisePropertyChanged("ResearcherId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svcResearcher.IResearcherService")]
    public interface IResearcherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResearcherService/GetResearchers", ReplyAction="http://tempuri.org/IResearcherService/GetResearchersResponse")]
        ResearchersWPF.UI.svcResearcher.Researcher[] GetResearchers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResearcherService/GetResearchers", ReplyAction="http://tempuri.org/IResearcherService/GetResearchersResponse")]
        System.Threading.Tasks.Task<ResearchersWPF.UI.svcResearcher.Researcher[]> GetResearchersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResearcherService/AddResearcher", ReplyAction="http://tempuri.org/IResearcherService/AddResearcherResponse")]
        int AddResearcher(string lastName, string firstName, string middleName, int departmentNumber, int age, string academicDegree, string position);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResearcherService/AddResearcher", ReplyAction="http://tempuri.org/IResearcherService/AddResearcherResponse")]
        System.Threading.Tasks.Task<int> AddResearcherAsync(string lastName, string firstName, string middleName, int departmentNumber, int age, string academicDegree, string position);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResearcherService/UpdateResearcher", ReplyAction="http://tempuri.org/IResearcherService/UpdateResearcherResponse")]
        void UpdateResearcher(ResearchersWPF.UI.svcResearcher.Researcher c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResearcherService/UpdateResearcher", ReplyAction="http://tempuri.org/IResearcherService/UpdateResearcherResponse")]
        System.Threading.Tasks.Task UpdateResearcherAsync(ResearchersWPF.UI.svcResearcher.Researcher c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResearcherService/DeleteResearcher", ReplyAction="http://tempuri.org/IResearcherService/DeleteResearcherResponse")]
        void DeleteResearcher(int researcherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResearcherService/DeleteResearcher", ReplyAction="http://tempuri.org/IResearcherService/DeleteResearcherResponse")]
        System.Threading.Tasks.Task DeleteResearcherAsync(int researcherId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResearcherServiceChannel : ResearchersWPF.UI.svcResearcher.IResearcherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResearcherServiceClient : System.ServiceModel.ClientBase<ResearchersWPF.UI.svcResearcher.IResearcherService>, ResearchersWPF.UI.svcResearcher.IResearcherService {
        
        public ResearcherServiceClient() {
        }
        
        public ResearcherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResearcherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResearcherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResearcherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ResearchersWPF.UI.svcResearcher.Researcher[] GetResearchers() {
            return base.Channel.GetResearchers();
        }
        
        public System.Threading.Tasks.Task<ResearchersWPF.UI.svcResearcher.Researcher[]> GetResearchersAsync() {
            return base.Channel.GetResearchersAsync();
        }
        
        public int AddResearcher(string lastName, string firstName, string middleName, int departmentNumber, int age, string academicDegree, string position) {
            return base.Channel.AddResearcher(lastName, firstName, middleName, departmentNumber, age, academicDegree, position);
        }
        
        public System.Threading.Tasks.Task<int> AddResearcherAsync(string lastName, string firstName, string middleName, int departmentNumber, int age, string academicDegree, string position) {
            return base.Channel.AddResearcherAsync(lastName, firstName, middleName, departmentNumber, age, academicDegree, position);
        }
        
        public void UpdateResearcher(ResearchersWPF.UI.svcResearcher.Researcher c) {
            base.Channel.UpdateResearcher(c);
        }
        
        public System.Threading.Tasks.Task UpdateResearcherAsync(ResearchersWPF.UI.svcResearcher.Researcher c) {
            return base.Channel.UpdateResearcherAsync(c);
        }
        
        public void DeleteResearcher(int researcherId) {
            base.Channel.DeleteResearcher(researcherId);
        }
        
        public System.Threading.Tasks.Task DeleteResearcherAsync(int researcherId) {
            return base.Channel.DeleteResearcherAsync(researcherId);
        }
    }
}
